/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=relay-worker/wrangler.jsonc --env-file=relay-worker/.dev.vars.example --include-runtime=false relay-worker/worker-configuration.d.ts` (hash: 4078775941477f8c37e28c60ee15dc1e)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "*";
	SESSION_RELAY: DurableObjectNamespace<import("./src/index").SessionRelay>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SessionRelay";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
